language: node_js
node_js:
  - "10"
  - "11"
  - "12"

cache:
  directories:
    - .yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set scripts-prepend-node-path true

script:
  - yarn build
  - yarn test-ci 
  - yarn eslint 
  - yarn dtslint
  - yarn wsrun -p 'fractal-component' --stages bundlesize

#after_script:
#  - npm run bundlesize