language: node_js
node_js:
  - "8"
  - "10"
  # lock to 11.10.1 due to https://github.com/facebook/jest/issues/8069
  - "11.10.1"

cache:
  directories:
    - .yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set scripts-prepend-node-path true

script:
  - yarn build
  - yarn test-ci 
  - yarn eslint 
  - yarn dtslint
  - yarn wsrun -p 'fractal-component' --stages bundlesize

#after_script:
#  - npm run bundlesize