language: node_js
node_js:
  - "8"
  - "10"
  - "11"

cache:
  directories:
    - .yarn

script:
  - yarn build
  - yarn test 
  - yarn eslint 
  - yarn dtslint
  - yarn wsrun -p 'fractal-component' --stages bundlesize

#after_script:
#  - npm run bundlesize