language: node_js
node_js:
  - "8"
  - "10"
  - "11"

cache:
  directories:
    - .yarn

script:
  - yarn build
  - yarn test 
  - yarn eslint 
  - npm run dtslint --prefix packages/core

#after_script:
#  - npm run bundlesize