name: Main CI Workflow

on: push

jobs:
  build-test:
    name: Build, Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup NPM
        run: npm config set scripts-prepend-node-path true
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn eslint
      - run: yarn dtslint
      - run: yarn wsrun -p 'fractal-component' --stages bundlesize